export enum TYPE_PRICE_MANAGEMENT {
    UPADOWN = "UPADOWN",
    NEWVALUE = "NEWVALUE",
}

export enum OPTION_PRICE_MANAGEMENT {
    INCREASE = "INCREASE",
    DECREASE = "DECREASE",
}

export enum PART_PRICE_MANAGEMENT {
    ALL = "ALL",
    BRAND = "BRAND",
    SELECTED = "SELECTED",
    CATEGORY = "CATEGORY",
}